project:
  type: website
  output-dir: "."

website:
  title: "James D. Gardner"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
        
      - text: Blog
        href: blog-listing.qmd

      - text: R Basics
        href: danl-200-quarto.qmd
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© James Gardner, 2024"

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
